version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: imersao-fullstack-nest-bank
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - bank-db
    env_file:
      - ./.env
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  bank-db:
    build: .docker/postgres
    container_name: imersao-fullstack-nest-bank-db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest

networks:
  default:
    external:
      name: codepix
